[project]
name = "package-management-r-python"
r_version = "4.4"

repositories = [
  {alias = "PPM", url = "https://packagemanager.posit.co/cran/latest"},
]

dependencies = [
    "dplyr",
    "tidyverse",
    "fs",
    "sf",
]
